language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

cache:
  directories:
    - vendor

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

branches:
  only:
  - master
  - /^v\d/

before_script:
- ./test/setup_vendor.sh

script:
  - php vendor/phpunit.phar
