<div class="controls">
    <?= $this->tabs ?>
</div>
<div class="content">
    <table class="name-value-table">
        <?php $event = $this->event($this->eventData); foreach ($displayColumns as $column): ?>
            <tr>
                <th><?= $this->columnHeader($column) ?></th>
                <td><?= $this->column($column, $event) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>

