<div class="controls">
    <?= $tabs ?>
</div>
<div class="content">
    <h2><?= $this->translate('Configure EventDB database backend') ?></h2>
    <?= $this->qlink(
        $this->translate('Create a New Resource'),
        'config/createresource',
        null,
        array(
            'class'            => 'button-link',
            'data-base-target' => '_next',
            'icon'             => 'plus',
            'title'            => $this->translate('Create a new resource'),
        )
    ) ?>
    <?= $form ?>
</div>
